language: python
sudo: required
cache: pip

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - pip install -U pip
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install Cython -vv
  - python setup.py build_ext -i
  - python setup.py install

script:
  - coverage run --source rspy/ -m pytest

after_success:
  - coveralls --exclude test