language: python
sudo: required
cache: pip

python:
  - "2.7"
  - "3.6"

virtualenv:
  system_site_packages: true

before_install:
  - pip install -U pip
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
#  - pip install coveralls
  - pip install coverage
  - python setup.py install

script:
  - coverage run --source respy/ -m pytest


#after_success:
#  - coveralls